### ISSUE TITLE
Compatibilidade com modulo do Pedro Teixeira

### ISSUE THREAD

**Issue by ticomarques** [rafaelstz/Biblioteca_Codigos_Magento#3]
Boa noite Rafael,

Eu gostaria de tirar uma duvida, esse modulo frete na pagina de produto não é compativel com o pedro teixeira não né ?

Abs
Tiago Marques

**Comment by rafaelstz** [comment]
Olá @ticomarques 

Atualmente há outro módulo que utilizo para esse fim, mantido pelos nossos devs na **Webjump**, ele é compatível com o módulo do Pedro Teixeira.
https://github.com/webjump/EcomDev_ProductPageShipping

**Comment by ticomarques** [comment]
Fala Rafael,
Eu reparei, vou testar o EcomDev.

Na verdade, eu estava pensando em parar de usar os módulos de consulta nos correios, e passar a usar o matrix rate, baixando os dados dos correios e rodando offline, seria mais seguro... porque não teriamos a variavel "webservice dos correios online". O que você acha ?

Será que vai funcionar o Matrix rate com as tabelas atualizadas, com o EcomDev ?

Eu sempre ouvi falar bastante de Webjump, eu era desenvolvedor na antiga Primordia, provalmente você deve conhecer. Eu cuidava do front-end da empresa, mas ela foi comprada pela Vtex, e eu decidi seguir meu rumo, e abrir a minha própria plataforma baseada no magento, assim como era a primordia.

Fico bastante feliz em conhecer você, e dê os parabéns para o resto da galera da WebJump, vocês estão de parabéns.

Abraços
Tiago Marques

**Comment by rafaelstz** [comment]
Vai funcionar sim, aqui na **Webjump** quando precisa utilizar Matrix Rate funciona normalmente, eu tenho um app para estimar frete na [Chrome Store](https://chrome.google.com/webstore/detail/c%C3%A1lculo-dos-correios/badfmkjhejbmeepnmiicdhmlabklioeg?utm_source=chrome-ntp-launcher) no qual tenho o mesmo problema de estabilidade com a API,  por isso recomendo usar essas API's:

### Postmon

Eles utilizam uma base online de ceps dos Correios para as buscas que ainda não estão cacheadas localmente no postmon.

```
   http://api.postmon.com.br/v1/cep/14177012
```

Além disso o código do postmon está aberto e disponível no [github](https://github.com/PostmonAPI/postmon)

### República Virtual

```
   http://cep.republicavirtual.com.br/web_cep.php?cep=14177012
```

Nós da Webjump agradecemos :smile: 
Abraços!
