### ISSUE TITLE
Magento 1.9.2.2

### ISSUE THREAD

**Issue by RichardVirag** [rafaelstz/Biblioteca_Codigos_Magento#6]
Não funciona na versão 1.9.2.2, não tem suporte pra ela?

**Comment by rafaelstz** [comment]
O que não está funcionando @RichardVirag?

**Comment by RichardVirag** [comment]
O Frete na página do produto, mesmo referenciando dessa forma:
`<?php echo $this->getChildHtml('Multikomerce_Freteproduto_cep') ?>`
E instalando os arquivos, não carrega na página... Na versão 1.6.2.0 do Magento funcionava

**Comment by rafaelstz** [comment]
@RichardVirag o módulo esta realmente desatualizado, precisa ser ajustado para a última versão do Magento 1, por meus clientes não estarem utilizando tanto Magento 1 eu não pretendo atualizar esse módulo por enquanto, mas aceito pull requests.
